openapi: 3.0.0
servers:
  - description: DINA - AAFC
    url: https://api.demo.dina-project.net
info:
  description: Collection API Schema
  version: "0.1.0"
  title: Collection Schema - DRAFT
  contact:
    email: info@dina-project.net
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
security:
  - OAuth2: []      
paths:
  /collection/api/v1/collecting-event:
    $ref: 'collectingEvent.yml#/paths/~1collection~1api~1v1~1collecting-event'
  /collection/api/v1/collecting-event/{Id}:
    $ref: 'collectingEvent.yml#/paths/~1collection~1api~1v1~1collecting-event~1{Id}'
  /collection/api/v1/collection:
    $ref: 'collection.yml#/paths/~1collection~1api~1v1~1collection'
  /collection/api/v1/collection/{Id}:
    $ref: 'collection.yml#/paths/~1collection~1api~1v1~1collection~1{Id}'
  /collection/api/v1/managed-attribute:
    $ref: 'collectionManagedAttribute.yml#/paths/~1collection~1api~1v1~1managed-attribute'
  /collection/api/v1/managed-attribute/{Id}:
    $ref: 'collectionManagedAttribute.yml#/paths/~1collection~1api~1v1~1managed-attribute~1{Id}'
  /collection/api/v1/material-sample:
    $ref: 'materialSample.yml#/paths/~1collection~1api~1v1~1material-sample'
  /collection/api/v1/material-sample/{Id}:
    $ref: 'materialSample.yml#/paths/~1collection~1api~1v1~1material-sample~1{Id}'
  /collection/api/v1/material-sample-action-definition:
    $ref: 'materialSampleActionDefinition.yml#/paths/~1collection~1api~1v1~1material-sample-action-definition'
  /collection/api/v1/material-sample-action-definition/{Id}:
    $ref: 'materialSampleActionDefinition.yml#/paths/~1collection~1api~1v1~1material-sample-action-definition~1{Id}'
  /collection/api/v1/material-sample-action-run:
    $ref: 'materialSampleActionRun.yml#/paths/~1collection~1api~1v1~1material-sample-action-run'
  /collection/api/v1/material-sample-action-run/{Id}:
    $ref: 'materialSampleActionRun.yml#/paths/~1collection~1api~1v1~1material-sample-action-run~1{Id}'
  /collection/api/v1/preparation-type:
    $ref: 'preparationType.yml#/paths/~1collection~1api~1v1~1preparation-type'
  /collection/api/v1/preparation-type/{Id}:
    $ref: 'preparationType.yml#/paths/~1collection~1api~1v1~1preparation-type~1{Id}'
  /collection/api/v1/institution:
    $ref: 'institution.yml#/paths/~1collection~1api~1v1~1institution'
  /collection/api/v1/institution/{Id}:
    $ref: 'institution.yml#/paths/~1collection~1api~1v1~1institution~1{Id}'
  /collection/api/v1/storage-unit-type:
    $ref: 'storageUnitType.yml#/paths/~1collection~1api~1v1~1storage-unit-type'
  /collection/api/v1/storage-unit-type/{Id}:
    $ref: 'storageUnitType.yml#/paths/~1collection~1api~1v1~1storage-unit-type~1{Id}'
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows: 
        password:
          tokenUrl: https://auth.demo.dina-project.net/auth/realms/dina/protocol/openid-connect/token
          refreshUrl: https://auth.demo.dina-project.net/auth/realms/dina/protocol/openid-connect/token
          scopes: {}